# Generated by Django 5.1.1 on 2025-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='begin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(),
        ),
    ]
