# Generated by Django 5.1.1 on 2025-02-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_leave_overdue_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='cancel_f',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='begin_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
