# Generated by Django 5.1.1 on 2025-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_leave_cancel_f_alter_leave_begin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pic',
            field=models.ImageField(blank=True, upload_to='certificate'),
        ),
    ]
