# Generated by Django 5.1.1 on 2025-02-10 10:57

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_certificate_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsport',
            name='have_file',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StuFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufile', models.FileField(default='', upload_to=base.models.StuFile.upload_to)),
                ('name', models.CharField(max_length=200)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.newsport')),
            ],
        ),
    ]
