# Generated by Django 5.1.1 on 2025-02-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_student_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='base.student'),
        ),
    ]
