# Generated by Django 5.1.1 on 2025-02-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_certificate_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufile',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to='base.newsport'),
        ),
    ]
